# this source code form is subject to the terms of the mozilla public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

## ------------------------------------------- Plugin Enable Properties
mosip.certify.integration.scan-base-package=io.mosip.certify.postgresdataprovider.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.data-provider-plugin=PostgresDataProviderPlugin
mosip.certify.plugin-mode=DataProvider


## --------------------------------------------DataProvider specific Certify configuration --------------------------------------------------- 
# set custom VC expiry, supports limited subset of ISO-8601 Duration format starting from days to seconds
# E.g. P21dT1h-2m3s for more information check javadoc of Duration.parse(String)
mosip.certify.data-provider-plugin.vc-expiry-duration:P730d
# Cache-Control max-age value for rendering templates
mosip.certify.rendering-template.cache-max-age-days=1
## ------------------------------------------- Plugin specific usecase properties ------------------------------------------------------------
## Postgres DB specific config

# Other supported value: [RsaSignature2018]
mosip.certify.data-provider-plugin.issuer.vc-sign-algo=Ed25519Signature2020
#mosip.certify.data-provider-plugin.issuer-public-key-uri=did:web:nambirajanr.github.io:DID:publickey#key-0
#mosip.certify.data-provider-plugin.issuer-uri=did:web:nambirajanr.github.io:DID:publickey
mosip.certify.data-provider-plugin.issuer-public-key-uri=did:web:durga0417.github.io:DID:dev1#key-0
mosip.certify.data-provider-plugin.issuer-uri=did:web:durga0417.github.io:DID:dev1
# below property to be removed in next release
mosip.certify.data-provider-plugin.rendering-template-id=
# below property to be removed in next release -- temporary workaround -> INJIWEB-1202
mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/
# maps OpenID scope to the DB query string where :id is fetched from the token's "sub" field
mosip.certify.data-provider-plugin.postgres.scope-query-mapping={\
    'mosip_identity_vc_ldp': 'select * from farmer_info where token_id=:id'\
  }

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.esignet.host=esignet.dst-stage.mosip.net
mosip.certify.domain.url=https://${mosip.injicertify.farmer.host}
mosip.certify.identifier=${mosip.certify.domain.url}
mosip.certify.authorization.url=https://${mosip.esignet.host}
mosip.certify.database.name=credential_partner
# conditionally set the SOFTHSM pin based on the setup requirements and fallback to the latter if former value is missing
mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.certify.security.pin}




mosip.certify.key-values={\
    'latest' : {\
              'credential_issuer': '${mosip.certify.identifier}',   \
              'authorization_servers': {'${mosip.certify.authorization.url}'}, \
              'credential_endpoint': '${mosip.certify.domain.url}${server.servlet.path}/issuance/credential', \
              'display': {{'name': 'Farmer VC', 'locale': 'en'}},\
              'credential_configurations_supported' : { \
                 'MosiLandFarmer' : {\
                    'format': 'ldp_vc',\
                    'scope' : 'mosip_identity_vc_ldp',\
                    'cryptographic_binding_methods_supported': {'did:jwk'},\
                    'credential_signing_alg_values_supported': {'Ed25519Signature2020'},\
                    'proof_types_supported': {'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256', 'ES256'}}},\
                    'credential_definition': {\
                      'type': {'VerifiableCredential','MosiLandFarmer'},\
                      'credentialSubject': {\
                        'date_of_birth': {'display': {{'name': 'Date Of Birth', 'locale': 'en'}}}, \
                        'id_type': {'display': {{'name': 'Id Type', 'locale': 'en'}}}, \
                        'farmer_id': {'display': {{'name': 'Farmer ID', 'locale': 'en'}}}, \
                        'issued_on': {'display': {{'name': 'Issued On', 'locale': 'en'}}}, \
                        'expired_on': {'display': {{'name': 'Expired On', 'locale': 'en'}}}, \
                        'fullname': {'display': {{'name': 'Full Name', 'locale': 'en'}}}, \
			            'gender': {'display': {{'name': 'Gender', 'locale': 'en'}}} \
                      }\
                    },\
                    'display': {{'name': 'Farmer VC', \
                                  'locale': 'en', \
                                  'logo': {'url': 'https://mosip.github.io/inji-config/logos/agro-vertias-logo.png','alt_text': 'Land logo'},\
                                  'background_color': '#ebfaff',\
                                  'background_image': { 'uri': 'https://mosip.github.io/inji-config/logos/agro-vertias-logo.png' }, \
                                  'text_color': '#000000'}},\
                    'order' : {"farmer_id","fullname","date_of_birth","gender","id_type","issued_on","expired_on"}\
            }\
        }\
    }\
}

